linters:
  enable:
    - deadcode
    - depguard
    - forbidigo
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - nolintlint
    - unused
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - io/ioutil: "`io/ioutil` is deprecated in Go 1.16, use `io` or `os` instead"
  forbidigo:
    forbid:
      - '^os\.(DirEntry|FileInfo|FileMode|PathError)$' # deprecated in Go 1.16, import them from 'io/fs' instead
      - '\.Readdir$' # deprecated in Go 1.16, use ReadDir instead
    exclude_godoc_examples: false
  gofmt:
    simplify: true
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  goimports:
    local-prefixes: github.com/datawire/ocibuild
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
issues:
  exclude-rules:
    ## Exceptions for borrowed code #################################

    - # Don't be too nitpicky on borrowed code
      path: 'borrowed_.*\.go$'
      linters:
        - gocritic
