linters:
  enable:
    - deadcode
    - depguard
    - forbidigo
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - lll
    - misspell
    - nolintlint
    - revive
    - unused
    - varnamelen
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - io/ioutil: "`io/ioutil` is deprecated in Go 1.16, use `io` or `os` instead"
  forbidigo:
    forbid:
      - '^os\.(DirEntry|FileInfo|FileMode|PathError)$' # deprecated in Go 1.16, import them from 'io/fs' instead
      - '\.Readdir$' # deprecated in Go 1.16, use ReadDir instead
    exclude_godoc_examples: false
  gofmt:
    simplify: true
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  goimports:
    local-prefixes: github.com/datawire/ocibuild
  lll:
    # mimic .editorconfig, plus 20 chars of slop
    line-length: 120
    tab-width: 8
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - lll # explanations are good, but often would just make things worse
  varnamelen:
    ignore-names:
      - bs # ByteS
      - fn # FunctioN
      - ok # OKay
      - tc # TestCase
      - i  # Index
      - 'a'
      - 'b'
issues:
  exclude-rules:
    ## Personal exceptions ##########################################

    - # Allow Cmp methods to be (a, b)
      linters: [revive]
      text: "receiver-naming: receiver name a should be consistent with previous receiver name"
      source: '^func \(a \S+\) Cmp\(b \S+\) int {'

    ## Exceptions for specifications ################################

    - # Allow PEPs to use a few UK-isms
      linters: [misspell]
      path: '^pkg/python/(pep|pypa/)'
      text: '`(behaviours?|standardised)` is a misspelling'
    - # Package names are based on specification names
      linters: [revive]
      text: "var-naming: don't use an underscore in package name"

    ## Exceptions for borrowed code #################################

    - # Don't be too nitpicky on borrowed code
      path: 'borrowed_.*\.go$'
      linters:
        - gocritic
        - varnamelen
