name: quality-assurance
on:
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - uses: actions/setup-python@v2
        with:
          python-version: '~3.9.9'
      - name: Show environment info
        run: |
          set -x
          go version
          python --version
          python3 --version
          pip --version
          pip3 --version
      - run: make check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - run: make lint
